### ISSUE TITLE
commercionetwork/docs/  - Transaction - Sending Document section 

### ISSUE THREAD

**Issue by raffaeleviola** [commercionetwork/commercionetwork#142]
https://docs.commercio.network/x/docs/#sending-a-document

1) A broken link must  be fixed 

<img width="781" alt="Schermata 2020-07-10 alle 11 36 01" src="https://user-images.githubusercontent.com/848884/87140424-c642a100-c2a1-11ea-8b34-d011eaac0fe4.png">

2) "supported metadata schemes section" link is an empty page 

<img width="693" alt="Schermata 2020-07-10 alle 11 43 03" src="https://user-images.githubusercontent.com/848884/87141152-ede63900-c2a2-11ea-80fd-926bc7afb20c.png">

Page

<img width="700" alt="Schermata 2020-07-10 alle 11 46 19" src="https://user-images.githubusercontent.com/848884/87141191-02c2cc80-c2a3-11ea-9d49-6c0f3e249cb1.png">

**Comment by marcotradenet** [comment]
@raffaeleviola The second link is not wrong, it's just that for now no scheme is supported yet

**Comment by raffaeleviola** [comment]
Ok 
in the page https://docs.commercio.network/x/docs/metadata-schemes.html#supported-metadata-schemes 

is better to write in the content 

"No scheme is supported yet"

for users clearness
