### ISSUE TITLE
Error adding tokens concurrently to different wallets

### ISSUE THREAD

**Issue by salessandrelli** [commercionetwork/commercionetwork#166]
## Summary of Bug

The following error occurs when adding tokens concurrently for 2 different wallet using faucet

_sign/broadcast message error: could not broadcast transaction to the Cosmos network: codespace sdk: unauthorized: signature verification failed; verify correct account sequence and chain-id, code 4_

## Steps to Reproduce

- Get 2 different wallet with same mnemonic and different LastDerivationPathSegment
- Add token concurrently to both wallets calling endpoint https://faucet-testnet.commercio.network/give?addr={{bech32Address}}&amount={{tokens}}

**Comment by marcotradenet** [comment]
Hello, I could not replicate the error. I derived the addresses from the 24 words using index 0 and 1, but the faucet worked correctly with both.

https://testnet.commercio.network/en/transaction/10B33A33867B8AB453A844351D36EAD702A722829CB51DAF0476868CB5469A94
https://testnet.commercio.network/en/transaction/2251052965CEFA5C63A2952227D62884608FCF4A66B01321AE05585F38F282AA

If you have tried to make calls at the same time or at a distance of one or two seconds to the faucet that may be the problem: transactions with a single account, that of the faucet, simultaneous or short distance do not work well. The problem, however, depends on cosmos.sdk.
@salessandrelli Could you try to repeat the procedure by making the second call after 7 or 8 seconds?

Thanks
