### ISSUE TITLE
Error adding token to any wallet

### ISSUE THREAD

**Issue by SimoneAcca** [commercionetwork/commercionetwork#189]
## Summary of Bug

The following error occurs when adding tokens:

`{"error":"sign/broadcast message error: could not get Account informations for address did:com:{{bech32Address}}: could not unmarshal node response: json: cannot unmarshal string into Go struct field AccountDataValue.result.value.account_number of type int64"}`

I tried also with different wallet 

## Steps to Reproduce

- Get a wallet with a mnemonic

- Add token by calling endpoint https://faucet-testnet.commercio.network/give?addr={{bech32Address}}&amount={{tokens}}

**Comment by marcotradenet** [comment]
This problem should have been solved
