### ISSUE TITLE
Procedure for buy a membership (Kyc module)

### ISSUE THREAD

**Issue by zenit70** [commercionetwork/commercionetwork#195]
In my opinion, the explanation of the procedure for buying a membership in the [documentation](https://docs.commercio.network/x/commerciokyc/#buying-a-membership) is  unclear; i.e. it is not clear that has to be the TSP to pay for the purchase of the membership.

**Comment by marcotradenet** [comment]
Try checking the description now https://staging.docs.commercio.network

**Comment by zenit70** [comment]
Now it's ok.
