### ISSUE TITLE
https://docs.commercio.network - link a Cosmos SDK transaction signing

### ISSUE THREAD

**Issue by raffaeleviola** [commercionetwork/commercionetwork#196]
Rif: https://docs.commercio.network/developers/create-sign-broadcast-tx.html#create-sign-and-send-a-transaction

Link `Cosmos SDK transaction signing` is now 404 must be updated to 
https://docs.cosmos.network/v0.41/core/transactions.html

<img width="1097" alt="Schermata 2021-02-17 alle 17 27 59" src="https://user-images.githubusercontent.com/848884/108234901-9156d080-7145-11eb-92fe-55d48dd57afc.png">

**Comment by marcotradenet** [comment]
Fixed: https://staging.docs.commercio.network
