### ISSUE TITLE
Incorrect "Getting the reward pool funds amount" endpoint

### ISSUE THREAD

**Issue by BenWolfaardt** [commercionetwork/commercionetwork#236]
## Summary of Bug

I've noticed that there is an error with the documentation for [Getting the reward pool funds amount](https://docs.commercio.network/x/commerciokyc/#getting-the-reward-pool-funds-amount) as neither endpoints, namely: `/commerciokyc/pool-funds` nor `/commerciokyc/accreditations-funds`, work.

## Solution

Change the endpoint to `/commerciokyc/funds` [here](https://github.com/commercionetwork/commercionetwork/edit/master/docs/x/commerciokyc/README.md)

**Comment by marcotradenet** [comment]
Resolved in #352
