### ISSUE TITLE
Panic - Module: Documents | Command: tx docs share 

### ISSUE THREAD

**Issue by BenWolfaardt** [commercionetwork/commercionetwork#240]
## Summary of Bug

When not specifying all of the desired parameters for the `tx docs share` command, the code exits with a panic. 

### Example of Desired Parameters 
```bash
[recipient] 
[document-uuid] 
[document-metadata-uri] 
[metadata-schema-uri] 
[metadata-schema-version]
[document-content-uri] 
[checksum-value] 
[checksum-algorithm]
```

## Version

git branch `main-3.0`

## Steps to Reproduce

For example, when leaving out the `[document-metadata-uri]` parameter, i.e.: 

<pre>
./commercionetworkd tx docs share \
 did:com:17zx4vs4fhy7c2yv4gzq5u9uqutlzqv7xyq9y38 \
 ce27b2c9-0f5f-4410-a2b6-d3f9fe9e00dc \
 <s>http://content.uri</s> \
 http://schema.uri \
 1.0.0 \
 http://content.uri \
 2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824 \
 sha-256 \
  --from did:com:1q7hszn4gtwdrpylldw32ex2p7cpd4qvj00yg8t \
  --node http://0.0.0.0:26657 \
  --chain-id commercionetwork \
  --fees 10000ucommercio \
  -y
</pre>

the code panics: 

```bash
panic: runtime error: index out of range [7] with length 7

goroutine 1 [running]:
github.com/commercionetwork/commercionetwork/x/documents/client/cli.CmdShareDocument.func1(0xc001007b80, {0xc001082c00, 0x7, 0x10})
        /home/ben/code/2_tradenet_3.0_ssh/commercionetwork_3.0/x/documents/client/cli/txDocument.go:61 +0x9c7
github.com/spf13/cobra.(*Command).execute(0xc001007b80, {0xc001082b00, 0x10, 0x10})
        /home/ben/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000ec3680)
        /home/ben/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /home/ben/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /home/ben/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:890
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0, {0xc000eb4f40, 0x1b})
        /home/ben/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/server/cmd/execute.go:36 +0x1eb
main.main()
        /home/ben/code/2_tradenet_3.0_ssh/commercionetwork_3.0/cmd/commercionetworkd/main.go:13 +0x2c	
```

## Proposed Solution

In `x/documents/client/cli/txDocument.go:61` 

```go
			if len(args) > 5 {
				contentURI = args[5]
				checksum = &types.DocumentChecksum{
					Value:     args[6],
					Algorithm: args[7],
				}
			}
```

We need to add a check, with appropriate error message, when not all of the parameters are parsed.

**Comment by SerigneCheikh98** [comment]
The first 5 parameters are mandatory. I added it in the command's help.
Furthermore, if you specify the `[checksum-value]` you have to specify the `[checksum-algorithm]` too.

Fixed it on branch `cheikh/fix-documents`.

**Comment by BenWolfaardt** [comment]
@SerigneCheikh98 this works wonderfully too, and the additional help is definitely a nice add!
