### ISSUE TITLE
Panic - Module: Commerciokyc | Command: tx commerciokyc buy

### ISSUE THREAD

**Issue by BenWolfaardt** [commercionetwork/commercionetwork#242]
## Summary of Bug

This issue is similar to issue [#240](https://github.com/commercionetwork/commercionetwork/issues/240). When not specifying the `membership-type` parameters for the `tx commerciokyc buy` command, the code exits with a panic. 

### Example of Desired Parameters 
```bash
[subscriber]
[membership-type]
```

## Version

git branch `main-3.0`

## Steps to Reproduce

For example, when leaving out specifically the `[membership-type]` parameter, i.e.: 

<pre>
./commercionetworkd tx commerciokyc buy \
 did:com:17zx4vs4fhy7c2yv4gzq5u9uqutlzqv7xyq9y38 \
 <s>gold</s> \
  --node http://0.0.0.0:26657 \
  --chain-id commercionetwork \
  -y
</pre>

> Please note that the above parameters aren't necessarily all parameters that need to be parsed.

the code panics: 

```bash
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/commercionetwork/commercionetwork/x/commerciokyc/client/cli.buyMembershipFunc(0xc000d5fd10, {0xc001077680, 0x1, 0x0})
        /home/ben/code/2_tradenet_3.0_ssh/commercionetwork/x/commerciokyc/client/cli/tx_membership.go:39 +0x45e
github.com/commercionetwork/commercionetwork/x/commerciokyc/client/cli.CmdBuy.func1(0xc001015400, {0xc001077680, 0x1, 0xa})
        /home/ben/code/2_tradenet_3.0_ssh/commercionetwork/x/commerciokyc/client/cli/tx_membership.go:19 +0x1e
github.com/spf13/cobra.(*Command).execute(0xc001015400, {0xc001077540, 0xa, 0xa})
        /home/ben/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000f03180)
        /home/ben/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /home/ben/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /home/ben/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:890
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0, {0xc0004eddc0, 0x1b})
        /home/ben/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.10/server/cmd/execute.go:36 +0x1eb
main.main()
        /home/ben/code/2_tradenet_3.0_ssh/commercionetwork/cmd/commercionetworkd/main.go:13 +0x2c
```

## Proposed Solution

In `x/commerciokyc/client/cli/tx_membership.go:39` 

```go
			membershipType := args[1]
```

We need to add a check, with an appropriate error message, when not all of the parameters are parsed.

**Comment by marcotradenet** [comment]
When the issue #243 is resolved the error should be fixed.

**Comment by BenWolfaardt** [comment]
@marcotradenet considering that issue #243 has now been solved, and after having just tested this, this issue is now also ready to close.
