### ISSUE TITLE
Error Module: Commerciokyc | Command: tx commerciokyc buy

### ISSUE THREAD

**Issue by BenWolfaardt** [commercionetwork/commercionetwork#243]
## Summary of Bug

This issue pertains to issue [#242](https://github.com/commercionetwork/commercionetwork/issues/242). When parsing the 2 requested parameters to the `CLI` for the `tx commerciokyc buy` command, an incorrect error message is returned. 

### Example of Desired Parameters 
```bash
[subscriber]
[membership-type]
```

## Version

git branch `main-3.0`

## Steps to Reproduce

When parsing

<pre>
./commercionetworkd tx commerciokyc buy \
  did:com:1zg4jreq2g57s4efrl7wnh2swtrz3jt9nfaumcm \
  gold \
  ...flags...
</pre>

The CLI returns with the following error message:

`Error: accepts 1 arg(s), received 2`

But it has clearly asked for us to parse it 2x parameters as per the "Example of Desired Parameters" section.

## Proposed Solution

In `x/commerciokyc/client/cli/tx_membership.go:17` 

```go
	func CmdBuy() *cobra.Command {
		cmd := &cobra.Command{
			Use:   "buy [subscriber] [membership-type]",
			Short: "Tsp buy a membership for subscriber",
			Args:  cobra.ExactArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				return buyMembershipFunc(cmd, args)
			},
		}
		flags.AddTxFlagsToCmd(cmd)

		return cmd
}
```

`Args:  cobra.ExactArgs(1),` change the expected arguments to `2`

**Comment by marcotradenet** [comment]
This should be fixed in this branch: https://github.com/commercionetwork/commercionetwork/tree/marco/commerciokyc-change-membership.     
The issue will be closed when the branch will be merged.

**Comment by marcotradenet** [comment]
@BenWolfaardt could you check if the command works fine?

**Comment by BenWolfaardt** [comment]
@marcotradenet yes, I confirm that the command works as anticipated, hai fatto bravo!
