### ISSUE TITLE
CLI Action: Commerciokyc | Command: tx commerciokyc invite

### ISSUE THREAD

**Issue by BenWolfaardt** [commercionetwork/commercionetwork#244]
## Summary of Bug

When trying to invite a did to buy a membership, who has already had a membership that has since been removed - using the `commercionetworkd tx commerciokyc remove-membership [subscriber] [flags]` command - the following error is returned in the JSON response: 

```json
	"raw_log":"failed to execute message; message index: 0: cannot invite existing user: unauthorized"
```

### Example of Desired Parameters 
```bash
[subscriber]
[flags]
```

## Version

git branch `main-3.0`

## Steps to Reproduce

When parsing

<pre>
./commercionetworkd tx commerciokyc remove-membership \
  did:com:17zx4vs4fhy7c2yv4gzq5u9uqutlzqv7xyq9y38 \
  --from did:com:1zg4jreq2g57s4efrl7wnh2swtrz3jt9nfaumcm \
  --node http://0.0.0.0:26657 \
  --chain-id commercionetwork \
  --fees 10000ucommercio \
  -y
</pre>

The CLI returns with the following error message:

```json
{
  "height": "62335",
  "txhash": "E39DC072F71C00C6D3007D26685BCC52C932452CDC5C717B73F7B4DE1C382CC2",
  "codespace": "sdk",
  "code": 4,
  "data": "",
  "raw_log": "failed to execute message; message index: 0: cannot invite existing user: unauthorized",
  "logs": [],
  "info": "",
  "gas_wanted": "200000",
  "gas_used": "53083",
  "tx": null,
  "timestamp": ""
}
```

## Proposed Solution

Is the membership correctly removed from the Blockchain?

**Comment by marcotradenet** [comment]
@BenWolfaardt I'm not sure to understand the issue: you can only invite a user one time with his address, and the address must not be present on the chain.     
Even if you remove the membership, it doesn't remove the invitation.

**Comment by BenWolfaardt** [comment]
Ciao @marcotradenet, thank you for clarifying.
