### ISSUE TITLE
Panic - Module: vbr | Command: tx vbr set-automatic-withdraw

### ISSUE THREAD

**Issue by BenWolfaardt** [commercionetwork/commercionetwork#247]
## Summary of Bug

When trying to perform the following command: `commercionetworkd tx vbr set-automatic-withdraw [0/1] [flags]` as per its "usage" definition the code panics with `panic message redacted to hide potentially sensitive system info: panic`

Similar to [#248](https://github.com/commercionetwork/commercionetwork/issues/248)

## Version

git branch `main-3.0`

## Steps to Reproduce

When attempting to perform the above command as per the below: 

```bash
./commercionetworkd tx vbr set-automatic-withdraw \
>  1 \
>  --from did:com:1nh557a0gmn0cwnrvefs7xll4986xsu27wnfzw2 \
>  --node http://0.0.0.0:26657 \
>  --chain-id commercionetwork \
>  --fees 100000ucommercio \
>  -y
```

the code responds with the following error: 

```json
{
  "height": "147374",
  "txhash": "FDD72924F96375AE07289B80D59CDAA5721CC6D35B179C2F4525E442DA0CF261",
  "codespace": "undefined",
  "code": 111222,
  "data": "",
  "raw_log": "panic message redacted to hide potentially sensitive system info: panic",
  "logs": [],
  "info": "",
  "gas_wanted": "200000",
  "gas_used": "51196",
  "tx": null,
  "timestamp": ""
}
```

Both values of `1` and `0` have been used with the same outcome.

**Comment by marcotradenet** [comment]
@BenWolfaardt I think this is not a issue about **Commerciokyc** module. The title of issue seems incorrect.

**Comment by marcotradenet** [comment]
@SerigneCheikh98 Remove command from module

**Comment by SerigneCheikh98** [comment]
@BenWolfaardt please note that the command has been deprecated and removed

**Comment by BenWolfaardt** [comment]
Perfect, thanks for letting me know.
