### ISSUE TITLE
Panic - Module: vbr | Command: tx vbr set-reward-rate

### ISSUE THREAD

**Issue by BenWolfaardt** [commercionetwork/commercionetwork#248]
## Summary of Bug

When trying to perform the following command: `commercionetworkd tx vbr set-reward-rate [rate] [flags]`, as per its "usage" definition, the code panics with `panic message redacted to hide potentially sensitive system info: panic`

Similar to [#247](https://github.com/commercionetwork/commercionetwork/issues/247)

## Version

git branch `main-3.0`

## Steps to Reproduce

When attempting to perform the above command as per the below: 

```bash
./commercionetworkd tx vbr set-reward-rate \
>  0.1 \
>  --from did:com:1nh557a0gmn0cwnrvefs7xll4986xsu27wnfzw2 \
>  --node http://0.0.0.0:26657 \
>  --chain-id commercionetwork \
>  --fees 100000ucommercio \
>  -y
```

the code responds with the following error: 

```json
{
  "height": "148188",
  "txhash": "B89313CD038BC71496651882A8FA485D6806ABBD6B4790747371B592DA757BCB",
  "codespace": "undefined",
  "code": 111222,
  "data": "",
  "raw_log": "panic message redacted to hide potentially sensitive system info: panic",
  "logs": [],
  "info": "",
  "gas_wanted": "200000",
  "gas_used": "51326",
  "tx": null,
  "timestamp": ""
}
```

Various values have been used for the `reward rate` with the same outcome.

**Comment by marcotradenet** [comment]
@SerigneCheikh98 Remove command. New param `vbr_earn_rate` should replaces `reward-rate`

**Comment by SerigneCheikh98** [comment]
@BenWolfaardt please note that the command has been deprecated and removed.

**Comment by BenWolfaardt** [comment]
Perfect, thanks for letting me know :)
