### ISSUE TITLE
CLI: Upgrade Module: all commands missing CLI definition.

### ISSUE THREAD

**Issue by BenWolfaardt** [commercionetwork/commercionetwork#249]
## Summary of Bug

*In the `upgrade` module, the below commands are all missing their definition in the `CLI` `-h` response.
* `delete`
* `schedule-height`
* `schedule-time`

## Version

git branch `main-3.0`

## Steps to Reproduce

`./commercionetworkd tx upgrade delete -h`
`./commercionetworkd tx upgrade schedule-height -h`
`./commercionetworkd tx upgrade schedule-time -h`

**Comment by marcotradenet** [comment]
@BenWolfaardt You can check now: the problem should be fixed with last update.

**Comment by BenWolfaardt** [comment]
@marcotradenet I see now that an `Example usage: commercionetworkd tx upgrade ...` text has been added to each of the above sub-commands. 

While this is very useful and would make anyone interacting with the chain through the `CLI`s life easier, it isn't what was meant by the issue. What was meant is that for all other commands, in the other modules, when performing `-h` there is normally a brief-phrase explaining the purpose of the command. 

Eg. for `./commercionetworkd tx gov deposit -h` it returns the following: 

```bash
Submit a deposit for an active proposal. You can
find the proposal-id by running "<appd> query gov proposals".

Example:
$ <appd> tx gov deposit 1 10stake --from mykey

Usage:
  commercionetworkd tx gov deposit [proposal-id] [deposit] [flags]

Flags:
  -a, --account-number uint      The account number of the signing account (offline mode only)
  -b, --broadcast-mode string    Transaction broadcasting mode (sync|async|block) (default "sync")
...
```

I'm referring to the `Submit a deposit for an active proposal.` phrase that is at the top of the `-h` output. This is what is missing for the `Upgrade Module`.

**Comment by SerigneCheikh98** [comment]
@BenWolfaardt please note that the module has been deleted and replaced by the cosmos one.

**Comment by BenWolfaardt** [comment]
@SerigneCheikh98 thanks for informing me :)
