### ISSUE TITLE
Historicization of DID documents proposal

### ISSUE THREAD

**Issue by fabtagliaferro** [commercionetwork/commercionetwork#250]
**Historicization of DID documents.** Proposed solutions: (i) with keeper <del>or (ii) using transaction events</del>

**Comment by marcotradenet** [comment]
@fabtagliaferro 
I think this issue could be closed, right?

**Comment by fabtagliaferro** [comment]
> @fabtagliaferro I think this issue could be closed, right?
Sure!

It looks like Github does not automatically close the issue if it is not linked to a PR to the default branch (I guess that's why this is still open)
