### ISSUE TITLE
Error Module: Commerciomint | Command: query commerciomint get-etps

### ISSUE THREAD

**Issue by BenWolfaardt** [commercionetwork/commercionetwork#251]
## Summary of Bug

After having successfully created a few ETP's (Exchange Trade Position) and performing the `commercionetworkd query commerciomint get-etps [user-addr] [flags]` an error message is returned. 

### Example of Desired Parameters 
```bash
[user-addr]
[flags
```

## Version

git branch `main-3.0`

## Steps to Reproduce

Confirming that we have ETP's for a particular user: 

```bash
./commercionetworkd query commerciomint get-all-etps \
  --node http://0.0.0.0:26657 \
  --output json \
  --chain-id commercionetwork
```

Response: 

```json
{
  "Positions": [
    {
      "owner": "did:com:1zg4jreq2g57s4efrl7wnh2swtrz3jt9nfaumcm",
      "collateral": "7",
      "credits": {
        "denom": "uccc",
        "amount": "10"
      },
      "created_at": "2021-07-22T13:18:44.598560074Z",
      "ID": "090ca0c2-cf00-4119-8307-b51413a00cf4",
      "exchange_rate": "0.610000000000000000"
    },
    {
      "owner": "did:com:1nh557a0gmn0cwnrvefs7xll4986xsu27wnfzw2",
      "collateral": "10",
      "credits": {
        "denom": "uccc",
        "amount": "10"
      },
      "created_at": "2021-12-13T12:55:05.485796703Z",
      "ID": "4cec4844-6142-4fc9-9444-be472843d483",
      "exchange_rate": "0.610000000000000000"
    },
    {
      "owner": "did:com:1nh557a0gmn0cwnrvefs7xll4986xsu27wnfzw2",
      "collateral": "10",
      "credits": {
        "denom": "uccc",
        "amount": "10"
      },
      "created_at": "2021-12-13T12:55:07.532028757Z",
      "ID": "a25b9cce-8ffa-4750-87b4-faf68631a3a3",
      "exchange_rate": "0.610000000000000000"
    },
    {
      "owner": "did:com:1nh557a0gmn0cwnrvefs7xll4986xsu27wnfzw2",
      "collateral": "10",
      "credits": {
        "denom": "uccc",
        "amount": "10"
      },
      "created_at": "2021-12-13T12:55:03.440493339Z",
      "ID": "c68ca443-6180-47bf-b015-53993cdc77df",
      "exchange_rate": "0.610000000000000000"
    }
  ],
  "pagination": {
    "next_key": null,
    "total": "4"
  }
}
```

We can thus clearly see that user `did:com:1nh557a0gmn0cwnrvefs7xll4986xsu27wnfzw2` clearly has a few ETP's.

When then performing the `commercionetworkd query commerciomint get-etps [user-addr] [flags]` command:

<pre>
./commercionetworkd query commerciomint get-etps \
  did:com:1nh557a0gmn0cwnrvefs7xll4986xsu27wnfzw2 \
  --node http://0.0.0.0:26657 \
  --output json \
  --chain-id commercionetwork
</pre>

The CLI returns with the following error message:

```
Eror: rpc error: code = Unknown desc = rpc error: code = Internal desc = Pagination error: rpc error: code = NotFound desc = Position with id 
/did:com:1nh557a0gmn0cwnrvefs7xll4986xsu27wnfzw2

uccc10"
      ��ݍ����*$4cec4844-6142-4fc9-9444-be472843d4832610000000000000000 not found!: unknown request
```

It seems that there is an incorrect interpretation of the `[user-addr]` parameter that needs to be parsed with this command. If we look at the `Position with id /did:com:1nh557a0gmn0cwnrvefs7xll4986xsu27wnfzw2` part of the error message it seems that the expression is trying to interpret the user address as the message `id`?

**Comment by marcotradenet** [comment]
@BenWolfaardt Can you check now the issue? It should be resolved

**Comment by BenWolfaardt** [comment]
@marcotradenet works perfectly, thank you very much!
