### ISSUE TITLE
Error Module: Government | Command: query government gov-address

### ISSUE THREAD

**Issue by BenWolfaardt** [commercionetwork/commercionetwork#253]
## Summary of Bug

When performing the `gov-address` command a nonsensical output is returned.

### Example of Desired Parameters 
```bash
[flags]
```

## Version

git branch `main-3.0`

## Steps to Reproduce

Confirming that we have ETP's for a particular user: 

```bash
./commercionetworkd query government gov-address  \
  --output json \
  --chain-id commercionetwork
```

Response: 

```json
{
  "governmentAddress":"\u0012+!\ufffd\nE=\n\ufffd#\ufffd\ufffd;\ufffd\u000eX\ufffd\u0019,\ufffd"
}
```

**Comment by marcotradenet** [comment]
@BenWolfaardt The error should be fixed. Can you try again. Thanks

**Comment by BenWolfaardt** [comment]
Tested and functioning, thanks @marcotradenet
