### ISSUE TITLE
Error Module: Upgrade | Command: query upgrade current

### ISSUE THREAD

**Issue by BenWolfaardt** [commercionetwork/commercionetwork#254]
## Summary of Bug

When performing the `current` command it returns with a "blank new line".

### Example of Desired Parameters 
```bash
[flags]
```

## Version

git branch `main-3.0`

## Steps to Reproduce

```bash
./commercionetworkd query upgrade current \
  --output json \
  --chain-id commercionetwork
```

A blank response is returned: 

```json

```

**Comment by marcotradenet** [comment]
@SerigneCheikh98 I think it should be better to print out a message like "No scheduled updates by now".

**Comment by marcotradenet** [comment]
@BenWolfaardt @SerigneCheikh98 this issue is supersed by the issue #261
