### ISSUE TITLE
Error Module: Vbr | Command: query vbr get-automatic-withdraw, get-reward-rate & pool-funds

### ISSUE THREAD

**Issue by BenWolfaardt** [commercionetwork/commercionetwork#255]
## Summary of Bug

The below subcomamands for `query vbr <below_command>` do not work: 

* `get-automatic-withdraw`
* `get-reward-rate`
* `pool-funds`

This error is essentially the same as [#252](https://github.com/commercionetwork/commercionetwork/issues/252)

## Version

git branch `main-3.0`

## Steps to Reproduce
 
Example of the Desired parameters for each of the below commands:

```bash
[flags]
```

When each of these commands is performed they receive the following errors:

### `get-automatic-withdraw`

```s
./commercionetworkd query vbr get-automatic-withdraw \
  --chain-id commercionetwork
```

error

```s
Error: no RPC client is defined in offline mode
```

### `get-reward-rate`

```s
./commercionetworkd query vbr get-reward-rate \
  --chain-id commercionetwork
```

error

```s
Error: no RPC client is defined in offline mode
```

### `pool-funds`

```s
./commercionetworkd query vbr pool-funds \
  --chain-id commercionetwork
```

error

```s
Error: could not get total funds amount: no RPC client is defined in offline mode
```

**Comment by marcotradenet** [comment]
@BenWolfaardt this issue should be fixed. Each command works fine.
