### ISSUE TITLE
Documentation Api - Authentication with password in the body 

### ISSUE THREAD

**Issue by ErreVi** [commercionetwork/commercionetwork#303]
In reference to https://docs.commercio.network/app_developers/commercioapi-authentication.html#get-the-id-token

Authentication takes place via endpoints auth/realms/commercio/protocol/openid-connect/token 

but in the example proposed here

  https://docs.commercio.network/app_developers/commercioapi-authentication.html#get-the-id-token

the password is passed as  `url encoded`
 
You can also pass it inside the json body ?

**Comment by marcotradenet** [comment]
No, it's not possible.
