### ISSUE TITLE
Wrong anchor associated with link 

### ISSUE THREAD

**Issue by ErreVi** [commercionetwork/commercionetwork#328]
Rif: https://docs.commercio.network/modules/did/#verificationmethod-fields-requirements

Clicking the link
<img width="916" alt="Schermata 2022-03-16 alle 17 05 39" src="https://user-images.githubusercontent.com/848884/158634973-809ca7b4-e30d-4106-bfce-e5c3c7df10f1.png">

This is the achor associated 
https://docs.commercio.network/modules/did/

**Comment by marcotradenet** [comment]
@ErreVi  This issue seems to have already been resolved by version 4.2.0. Do you confirm?
