### ISSUE TITLE
Faucet-testnet /invite result HTTP/1.1 500 Internal Server Error

### ISSUE THREAD

**Issue by davide-perego-commercio** [commercionetwork/commercionetwork#331]
Following documentation at
https://developers-guide.commercio.network/2-commercio-account/2.7-chapter.html#invite

yesterday I was having an error using the /invite method both with code as with this equivalent simple shell command:

```
curl -i "https://faucet-testnet.commercio.network/invite?addr=did%3Acom%3A1crltcqwt9r0tpy9v0jnuu7lw6snl5k2wez8cca"

HTTP/1.1 500 Internal Server Error
Server: nginx/1.14.0 (Ubuntu)
Date: Wed, 23 Mar 2022 15:58:58 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 252
Connection: keep-alive
X-Content-Type-Options: nosniff

{"error":"sign/broadcast message error: could not broadcast transaction to the Cosmos network: codespace sdk: signature verification failed; please verify account number (11), sequence (9121) and chain-id (commercio-testnet11k): unauthorized, code 4"}
```

Can you help me with the problem or tell me if I am assuming it wrong?

Thanks
Davide

**Comment by marcotradenet** [comment]
Hello, 

that documentation is outdated (refers to version 2.1.2). Try requesting the tokens directly from the faucet without invite.
