### ISSUE TITLE
Vbr epoch identifier doesn't accept EpochHour

### ISSUE THREAD

**Issue by marcotradenet** [commercionetwork/commercionetwork#343]
## Summary of Bug

Vbr epoch identifier doesn't accept `EpochHour` in `ValidateBasic` of `MsgSetParams`

## Version

v3.0.1

## Steps to Reproduce

Send a `MsgSetParams` with  value  'hour' in `epochIdentifier` field.     
Chain rejects the message with the error 
```
invalid epoch identifier: hour
```

**Comment by fabtagliaferro** [comment]
@marcotradenet shall we accept `EpochMonth`, too? It's allowed in [keeper.go](https://github.com/commercionetwork/commercionetwork/blob/a350e03980c3ad144ba108063212609e10d71551/x/vbr/keeper/keeper.go#L149)

**Comment by marcotradenet** [comment]
Don't include `EpochMonth`. On the keeper.go there is only control over how much an identifier equals versus time. The controls are on `/x/vbr/keeper/msg_server_vbr.go` and `/x/vbr/types/msgs.go`

**Comment by marcotradenet** [comment]
Resolved in #348
