### ISSUE TITLE
Add CCC fee in docker testnet nodes

### ISSUE THREAD

**Issue by pasqenr** [commercionetwork/commercionetwork#358]
## Summary of Bug

Hi, I've found out that the [`testnet`](https://github.com/commercionetwork/commercionetwork/blob/master/cmd/commercionetworkd/cmd/testnet.go) command  , by default, would generate nodes configurations with [only `ucommercio` fee denom](https://github.com/commercionetwork/commercionetwork/blob/master/cmd/commercionetworkd/cmd/testnet.go#L118).

To have a network where we are been able to pay in `CCC` too, we managed to do it by manually changing the generated `app.toml` value:

```toml
minimum-gas-prices = "0.000006ucommercio"
```

to

```toml
minimum-gas-prices = "0.000006ucommercio,0.000006uccc"
```

I've seen that this seems a flag argument so maybe a change in the [Makefile](https://github.com/commercionetwork/commercionetwork/blob/master/Makefile#L162) is more appropriate for this issue.

Side note: the description in the `app.toml` reports this format:

```toml
# [...] specified in this config (e.g. 0.25token1;0.0001token2).
```

but, instead, the correct one is with a comma `,` between the denom, not a semicolon `;`.

## Version

69c4c62be777b731e7967956f2cf7ba196ca322a

## Steps to Reproduce

1. Clone the repository
    
    ```shell
    git clone git@github.com:commercionetwork/commercionetwork.git && cd commercionetwork
    ```

2. Build the images:

    ```shell
    make build-image-to-download-libraries
    ```

4. Setup the nodes directories and genesis files:
    
    ```shell
     make localnet-setup
     ```

5. Check the gas price generated value:
    
     ```shell
     grep -i minimum-gas-prices build/node0/commercionetwork/config/app.toml
     # minimum-gas-prices = "0.000006ucommercio"
     ```

**Comment by marcotradenet** [comment]
@pasqenr Can I close this issue? Thanks

**Comment by pasqenr** [comment]
> @pasqenr Can I close this issue? Thanks

Yes and thank you for the fix.
