### ISSUE TITLE
Courtesy Link to swagger Api on docs.commercio.network

### ISSUE THREAD

**Issue by ErreVi** [commercionetwork/commercionetwork#363]
## Summary of Bug
It could be useful having a courtesy link to Swagger lcd on docs.commercio.network

* https://lcd-testnet.commercio.network/
* https://lcd-mainnet.commercio.network/

**Comment by marcotradenet** [comment]
@ErreVi Where do you think is a good place to put them?

**Comment by ErreVi** [comment]
I suggest to provide a table in the sections 
https://docs.commercio.network/#test-net-vs-main-net  indicating the main endpoint of the environement 

### Testnet endpoint & Resources

|Description| Endpoint |
| --- | --- | 
| Explorer |  [testnet.commercio.network](https://testnet.commercio.network/)  | 
| LCD |  (https://lcd-testnet.commercio.network/)  | 
| RPC |    |
| GRPC |    |
| Faucet |   https://faucet-testnet.commercio.network/give?addr=#WALLET_ADDRESS#&amount=#AMOUNT#  |
|Commercio wallet app IOS  |  https://apps.apple.com/it/app/commerc-io/id1397387586   |
|Commercio wallet app Android |  https://play.google.com/store/apps/details?id=io.commerc.preview.one   |
|Commercio  app |   [dev.commercio.app](https://dev.commercio.app/)   |
|Commercio  app API |   https://dev-api.commercio.app/v1/swagger/index.html   |


### Mainnet endpoint & Resources

| --- | --- | 
| Explorer |  [mainnet.commercio.network](https://mainnet.commercio.network/)  | 
| LCD |  https://lcd-mainnet.commercio.network/  | 
| RPC |    |
| GRPC |    |
|Commercio wallet app IOS  |   https://apps.apple.com/it/app/commerc-io/id1397387586  |
|Commercio wallet app Android |  https://play.google.com/store/apps/details?id=io.commerc.preview.one   |
|Commercio  app |  [commercio.app](https://commercio.app/)   |

**Comment by marcotradenet** [comment]
@ErreVi Can you check it: https://docs.commercio.network/#main-net-vs-test-net
