### ISSUE TITLE
Buildsystem overhaul

### ISSUE THREAD

**Issue by alessio** [commercionetwork/commercionetwork#50]
The buildsystem looks pretty old and is no longer in sync with `gaia`'s latest changes.

I'd advise to take inspiraton from `github.com/cosmos/gaia`'s Makefile latest changes as in: just copy it and adapt all the relevant parts to suit `commercionetwork` custom's design and needs.

Examples:
* The envvar `VERSION` should be computed from `git describe`'s output.
* Same goes for `COMMIT`
* Cosmos SDK supports passing ldflags at build time in order to customise app's version field, e.g.:

```
ldflags = -X github.com/cosmos/cosmos-sdk/version.Name=cn \
                  -X github.com/cosmos/cosmos-sdk/version.ServerName=cnd \
                  -X github.com/cosmos/cosmos-sdk/version.ClientName=cncli \
                  -X github.com/cosmos/cosmos-sdk/version.Version=$(VERSION) \
                  -X github.com/cosmos/cosmos-sdk/version.Commit=$(COMMIT) \
                  -X "github.com/cosmos/cosmos-sdk/version.BuildTags=$(build_tags_comma_sep)"
```

**Comment by gsora** [comment]
#57 integrated all those suggestions.

**Comment by gsora** [comment]
#57 has been merged, so I believe this issue can be closed.
