### ISSUE TITLE
codecov.io integration

### ISSUE THREAD

**Issue by alessio** [commercionetwork/commercionetwork#51]
Please provide CI integration with codecov.io and put a coverage status badge on top of the `Makefile`.

You may find some useful examples on how to do this in `gaia`'s `Makefile`:
https://github.com/cosmos/gaia/blob/master/.circleci/config.yml

In particular, I'd advise to take a look at the CircleCI `test-cover` and `upload-coverage` targets.

**Comment by RiccardoM** [comment]
Closed with #36
