### ISSUE TITLE
Use go.uuid instead of manually validating UUIDs

### ISSUE THREAD

**Issue by gsora** [commercionetwork/commercionetwork#62]
In `x/docs/internal/types/document.go`, the function `validateUUID` uses a `regexp` based approach to validate UUIDs:

```go
func validateUUID(uuid string) bool {
	regex := regexp.MustCompile(`[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}`)
	return regex.MatchString(uuid)
}
```

Re-creating the `regex` struct every time this function gets called is extremely time consuming, and since `go.uuid` is already a dependency of this project, I propose an alternative approach:

```go
func validateUUID(uuidStr string) bool {
	_, err := uuid.FromString(uuidStr)
	if err != nil {
		return false
	}
	return true
}
```

To test how much this change would affect the speed UUID validation, I did some benchmarks with and without `regexp`:

```
goos: linux
goarch: amd64
pkg: uuidcheck
Benchmark_validUUIDRegex-16       114060             10063 ns/op            9423 B/op         68 allocs/op
Benchmark_validUUIDLib-16       10236776               123 ns/op              48 B/op          1 allocs/op
PASS
ok      uuidcheck       2.643s
```

**Comment by RiccardoM** [comment]
Closed with #63
