### ISSUE TITLE
cnd runtime error

### ISSUE THREAD

**Issue by marcotradenet** [commercionetwork/commercionetwork#7]
[errori.txt](https://github.com/commercionetwork/commercionetwork/files/3471882/errori.txt)
## Summary of Bug

In runtime execution reports this error
```
panic: interface conversion: interface is nil, not types.KVStore
```

51678d2d026940083355c2d9a4b91c4267421d30

## Steps to Reproduce

```
rm -r ~/.cnd
cnd unsafe-reset-all
cnd init testchain --overwrite
```
**if you need create wallet**
```
cncli keys add jack
```
and complete 
```
cnd add-genesis-account $(cncli keys show jack --address) 10000000000000ucommercio
cnd gentx --name jack --amount 100000000ucommercio
cnd collect-gentxs
cnd start
```

**Comment by RiccardoM** [comment]
Fixed with 92437d5e5f274659fa9a4b6ac984fd4455dcff68
