### ISSUE TITLE
Combine same methods tests together

### ISSUE THREAD

**Issue by RiccardoM** [commercionetwork/commercionetwork#70]
In the current test suite we have multiple test methods for the same functions. 

Some examples are 

```
Test_handleAddTrustedSigner_InvalidGovernment
Test_handleAddTrustedSigner_ValidGovernment

TestKeeper_InviteUser_NoInvite
TestKeeper_InviteUser_ExistentInvite
```

I think it would be better to combine those kind of tests into the same test functions, to reduce the number of methods defined. 
To do so, we can use the method introducted by @gsora inside [`Test_validateUUID`](https://github.com/commercionetwork/commercionetwork/blob/master/x/docs/internal/types/document_test.go#L23)

**Comment by gsora** [comment]
Great idea!

I'll aggregate this kind of tests for `x/docs` in #69
