### ISSUE TITLE
AppendAllIfMissing could be incorporated in AppendIfMissing

### ISSUE THREAD

**Issue by gsora** [commercionetwork/commercionetwork#75]
Right now there are various `AppendIfMissing` methods for various slice types.

For some of those types another method called `AppendAllIfMissing` is defined, which essentially calls `AppendIfMissing` for each element in the input slice:

```go
func (t Type) AppendAllIfMissing(otherT Type) Type {
	result := receipts
	for _, thing := range otherT {
		result, _ = result.AppendIfMissing(thing)
	}
	return result
}
```

The presence of those two version of the same concept is redundant.

I propose we change `AppendIfMissing` to use variadic arguments:

```go
func (t Type) AppendIfMissing(otherT ...T) T{
	result := receipts
	for _, thing:= range otherT {
		result, _ = result.AppendIfMissing(thing)
	}
	return result
}
```

The new `AppendIfMissing` achieves the same effect as `AppendAllIfMissing` and its original version, 
by reducing the amount of cognitive load needed to do such simple operation:

1. adding a simple element: `t.AppendIfMissing(element)`
2. adding a slice of elements: `t.AppendIfMissing(elements...)`

**Comment by gsora** [comment]
Reviewers please let me know what you think about this proposal, side-effect/determinism-wise.

**Comment by RiccardoM** [comment]
I'm in favor of this change. It should not change much performance/determinism-wise
