### ISSUE TITLE
MsgSetIdentity has wrong default Context

### ISSUE THREAD

**Issue by gsora** [commercionetwork/commercionetwork#79]
## Summary of Bug

The W3C Context URL embedded in MsgSetIdentity transactions currently gives 404: https://testnet.commercio.network/it/transaction/6C767BEE1CE04F7B887E9A23495F8F7E8D5F4A6F3B7B7275294B1CB0AB3F84DA

## Version

v.1.3.3

## Steps to Reproduce

Create a MsgSetIdentity transaction.

The correct URL should be https://www.w3.org/ns/did/v1

**Comment by bragaz** [comment]
solved in commit aee18a47d9f3803a3960b6b0c94cbf0cb0f13a1c

**Comment by bragaz** [comment]
solved in commit aee18a47d9f3803a3960b6b0c94cbf0cb0f13a1c
